import {
  JOB_LETTER_PAPER_SIZES,
  JOB_LETTER_FONTS,
  JOB_LETTER_FONT_SIZES,
  JOB_LETTER_LINE_HEIGHTS,
  JOB_LETTER_ALIGNMENTS,
  JOB_LETTER_INDENTATIONS,
  JOB_LETTER_DATE_PLACEMENTS,
  JOB_LETTER_SIGNATURE_PLACEMENTS,
  JOB_LETTER_LAMPIRAN_OPTIONS,
} from "@/lib/constants";

export const PAPER_SIZES = JOB_LETTER_PAPER_SIZES;
export const FONTS = JOB_LETTER_FONTS;
export const FONT_SIZES = JOB_LETTER_FONT_SIZES;
export const LINE_HEIGHTS = JOB_LETTER_LINE_HEIGHTS;
export const ALIGNMENTS = JOB_LETTER_ALIGNMENTS;
export const INDENTATIONS = JOB_LETTER_INDENTATIONS;
export const DATE_PLACEMENTS = JOB_LETTER_DATE_PLACEMENTS;
export const SIGNATURE_PLACEMENTS = JOB_LETTER_SIGNATURE_PLACEMENTS;
export const LAMPIRAN_OPTIONS = JOB_LETTER_LAMPIRAN_OPTIONS;
